### PR TITLE
feat: add muc user list on joindialog

### PR DESCRIPTION
**Pull request by mightymop**
... on hover over a search icon when group is not empty

### CODE REVIEW

**Comment by sualko** [comment]
Congratulation! You opened the :one::zero::zero::zero:th ticket. :tada:

**Comment by sualko** [comment]
I think the more appropriate place for the member list would be the next screen which shows also all other room information. So can you move your code to the `continueHandler`?

**Comment by mightymop** [comment]
> 
> 
> I think the more appropriate place for the member list would be the next screen which shows also all other room information. So can you move your code to the `continueHandler`?

yes of course..

**Comment by mightymop** [comment]
> Congratulation! You opened the 1️⃣0️⃣0️⃣0️⃣th ticket. 🎉

🍻

**Comment by sualko** [comment]
> i only have to think abou what to do :D

Here you go: https://github.com/jsxc/jsxc/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement

**Pull request closed without merging**
