### PR TITLE
Update fr.json and fix typos

### PR DESCRIPTION
**Pull request by HLFH**
Hi,

Thanks to merge.

Sincerely yours,
Your greatest fan.

### CODE REVIEW

**Comment by sualko** [comment]
Translations are handled via https://webtranslateit.com/en/projects/10365-JSXC, please create an account and add your modifications there. If you have no time to do so, I will try to add the missing segments by myself, but this could be kind of difficult. e.g. I do not know which word ist better for nickname: Surnom or Pseudo.

**Comment by HLFH** [comment]
@sualko See https://fr.wikipedia.org/wiki/Pseudonyme

`Pseudo` se distingue du `surnom` en ceci qu'il est choisi par la personne qui le porte au lieu de lui être attribué par un tiers.

A `surnom` is attributed to you by your family and your friends.
A `pseudo` is attributed by you sometimes in an IRL context, and often when you want to use Internet in a semi-anonymous manner.

I created an account and I'll do that.

**Comment by HLFH** [comment]
@sualko I made the needed updates and changes. Could we get the last `fr.json` in the master branch of `jsxc`?

**Comment by sualko** [comment]
Not in master, but in develop: https://github.com/jsxc/jsxc/commit/a14cfde5db73135d5ff2a11bcc69fe7b3d1a46b8

Thank you for your effort.

**Comment by HLFH** [comment]
@sualko FYI, I updated also `Chatty` and translated it to `Bavard`. It's more accurate than the `tchatty` translation that does not mean anything in French. Sorry to ask you another commit to `develop` :)

**Comment by sualko** [comment]
I will update all locals before the next beta release. Otherwise my log is full of "update locales" commits.

**Comment by HLFH** [comment]
Ok thanks!!

**Pull request closed without merging**
