### PR TITLE
feat: api to create and join muc rooms

### PR DESCRIPTION
**Pull request by jlemangarin**
feat https://github.com/jsxc/jsxc/issues/805

### CODE REVIEW

**Comment by jlemangarin** [comment]
Thank you for your comments, I'll work on it

**Comment by jlemangarin** [comment]
I made some modification but not sure it's enough, let me know what you think ! :)

**Comment by sualko** [comment]
I fixed the shortcomings of my previous solution and hopefully it fulfills your needs. Please checkout 5fc77cf96beed7900a20e108df42e976320ae0a0 and test if some functionality is missing. Here is an example:

```
let jsxc = new JSXC();
// connecting and so on...
let account = jsxc.getAccount();
let contact = account.createMultiUserContact('foobar@conference.localhost', 'cool_nick');
contact.join(); // will join an existing room, or will create an instant room

// optional
let jsonRoomForm = contact.getRoomConfigurationForm();
// process config and create new json form
let jsonRoomConfig = {
  type: 'submit',
  fields: [...]
};
contact.submitRoomConfigurationForm(jsonRoomConfig);
```

**Comment by jlemangarin** [comment]
Yeah it's fine but just, the setBookmark and setAutoJoin seems not to work here, there is no storage:bookmark request. Do you know why ?

**Comment by sualko** [comment]
That's intentionally. Just call `addToContactList` on the contact object. I will add a section to our documentation.

**Pull request closed without merging**
