### PR TITLE
Updated the readme

### PR DESCRIPTION
**Pull request by drewpotter**
Initial work mentioned in the readme.

### CODE REVIEW

**Comment by drewpotter** [comment]
Sorry! Made an incorrect pull request!!

**Comment by sualko** [comment]
No problem :wink:. If you give us more information about your fork, we can mention you on our homepage, twitter and so on.

Btw. [MPL is GPL compatible](https://www.gnu.org/licenses/license-list.en.html#MPL-2.0).

**Comment by drewpotter** [comment]
Ah many thanks! I read somewhere online that the MPL is compatible with the GPL as long as it doesn't specify the following:

```
Exhibit B - "Incompatible With Secondary Licenses" Notice
---------------------------------------------------------

  This Source Code Form is "Incompatible With Secondary Licenses", as
defined by the Mozilla Public License, v. 2.0.
```

But I noticed that otr seems to have this line at the bottom of the license.

My fork is just simply a way of integrating your great code with what I am working on; dinarly; a mixed/augmented/virtual reality e-learning platform which will come loaded with educational content. 
http://www.github.com/dinarly/dinarly


The materials will all be AGPLv3 and the video narrative will be all rights reserved but freely distributed to those who want to learn 😉

**Comment by sualko** [comment]
I talked to the OTR author and he referred to Q25 of the [MPL FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/).

> Q25: What happens if someone doesn't use the per-file boilerplate, and just ships a copy of the full MPL 2 with their code?
The code is licensed under the plain MPL 2. It is not considered Incompatible with Secondary Licenses. Making code Incompatible with Secondary Licenses requires an active choice on the part of the licensor; **it is not the default**. The notice in Exhibit B is not considered "attached" merely by being present as the Exhibit B of a copy of the full MPL 2.

As he doesn't include the Exhibit B in his bundle, it's fine to use his OTR library as part of an GPL application :tada:.

**Comment by drewpotter** [comment]
Wow many thanks! That is awesome! I will not be removing OTR then. Although I need to make some other changes to jsxc to integrate it with mixed/augmented/virtual reality using Mozilla A-Frame. I will make any improvements or changes to jsxc available under the MIT license, so that if anything mutually beneficial happens which will benefit jsxc then you can include those changes. I am well aware of the issues of AGPLv3 and then making improvements into other projects. So I want to give back anything I can to your project. Thanks for finding out about this license issue!

**Comment by sualko** [comment]
> which will benefit jsxc then you can include those changes

Sounds great. I'm looking forward to those changes :wink:

**Pull request closed without merging**
