### PR TITLE
add jsbeautifier

### PR DESCRIPTION
**Pull request by sualko**
Once again this commit has a huge impact on all forks, but I think it is unavoidable to get clean code.

Pros and Cons?

Do you think this is feasible?

@Zauberstuhl @johangm90 @dimaursu @AugierLe42e @jhass

### CODE REVIEW

**Comment by shaggybb** [comment]
+1

**Comment by sualko** [comment]
Maybe [grunt-sass-format](https://www.npmjs.com/package/grunt-sass-format) would be also interesting.

**Comment by Zauberstuhl** [comment]
cons: well, the obvious one ;)
I'll wait for the next release before I start hurting myself with conflicts.

Besides my crying I am good with it. Thanks for your work!

**Comment by sualko** [comment]
How should the order be?

1) diaspora merge jsxc/master, jsxc/develop merge jsxc/jsbeautifier, disapora merge jsxc/develop
2) jsxc/develop merge jsxc/jsbeautifier, disapora merge jsxc/develop
3) diaspora run beautifier, jsxc/develop merge jsxc/jsbeautifier, disapora merge jsxc/develop

**Comment by sualko** [comment]
I will merge this after the release of 2.0.1.

**Pull request merged**
