### PR TITLE
Development/beta example

### PR DESCRIPTION
**Pull request by anonimal**
I like the showWaitAlert feature in the example's #form and think that it would help maintain continuity between both of the included examples. I know that anyone could hack their own event, but I think that this (or something like this) should be included instead of having an idle UI that waits for the backend to connect.

Also included are some very minor formatting cleanup.

### CODE REVIEW

**Comment by sualko** [comment]
I will not merge this pr, but I will leave it open until I improved the example.

**Comment by sualko** [comment]
One more improvement 21157c23b83037539cfd4436431c901b410ac243

**Comment by sualko** [comment]
fc1b2f46419f5c07f762ed096ad65c36930fee20 should obsolete your pr.

screen shot 2015-05-27 at 15 36 44

**Comment by anonimal** [comment]
Very nice. When will you merge into master?

**Pull request closed without merging**
