### PR TITLE
Update uk-UA.json

### PR DESCRIPTION
**Pull request by ostasevych**
Updated Ukrainian translation

### CODE REVIEW

**Comment by sualko** [comment]
Thanks for your contribution. What's the difference to #869?

Btw it's easier to make those changes at our translation website: https://webtranslateit.com/en/projects/10365-JSXC/

**Comment by ostasevych** [comment]
I found that several translations are not fitting well in the chat window with the length of symbols, so I just shortened them. No significant improvements. Besides, have you thought about using some web-based translation system, eg crowding, which is used by Pix-Art, eg?

**Comment by sualko** [comment]
> I found that several translations are not fitting well in the chat window with the length of symbols, so I just shortened them. No significant improvements.

But what is the difference to your other pull request? See #869 

> Besides, have you thought about using some web-based translation system, eg crowding, which is used by Pix-Art, eg?

Jep. That was the link I posted earlier: https://webtranslateit.com/en/projects/10365-JSXC/

**Comment by ostasevych** [comment]
Ah, yes! With this quarantine my memory became weak. Please, ignore pull request, I made changes via weblate. Sorry for confusing you.

**Pull request closed without merging**
