### PR TITLE
fix http upload discovery

### LINKED ISSUE #457: http upload not detected on ejabberd
I am using jsxc for nextcloud version 3.1.1 with ejabberd 16.01 and I am trying to send an image to the conversations app on Android but jsxc does not detect http upload support in the ejabberd server.  I am seeing in the web console "192.168.0.211 does not support http upload" but the conversationsn app detects http upload in ejabberd and is able to send files to jsxc which appear as links.  Conversations seems to query upload.192.168.0.211 to get the http upload feature but jsxc does not do this.

### PR DESCRIPTION
**Pull request by sualko**
fix #457

@PeterEdens @ChristianTacke can you verify that this fix works for you or that this fix does not break anything for you?

- [x] make max file size optional

### CODE REVIEW

**Comment by PeterEdens** [comment]
This fix works for me and http upload is discovered.  There are some issues now when trying to upload a file:

1. The maxSize value is null so it reports 'File too large for http upload.', I made a change to get past this at line 2467:

jsxc.fileTransfer.fileSelected = function(jid, msg, file) {
   var bid = jsxc.jidToBid(jid);
   var maxsize = jsxc.options.get('httpUpload').maxSize;

   if (file.transportMethod !== 'webrtc' && jsxc.xmpp.httpUpload.ready && (maxsize != null && file.size > maxsize)) {
      jsxc.debug('File too large for http upload.');

This tests for null and allows uploads of all sizes if it is not set.

2. When I try to upload a file I get an error in the browser console:
Refused to connect to 'https://mybox-211.domain.com:5443/upload/09e9b59bf946ac32c93514422f7f4341afe775d9/SelLst5m1fapp4khbCAf1BMxL3yV6PP5BoP1IrtY/1.jpg' because it violates the following Content Security Policy directive: "connect-src 'self' wss://mybox-211.domain.com 192.168.0.211 ".

**Comment by sualko** [comment]
> This tests for null and allows uploads of all sizes if it is not set.

Great catch. I was assuming that a max file size is required, but the spec says it is optional. Thanks for that hint.

> When I try to upload a file I get an error in the browser console

You can add `mybox-211.domain.com:5443` to the list of external services in your nextcloud admin settings (last option in the jsxc section). There is also a auto discovery option for this.

**Comment by PeterEdens** [comment]
I tried this but then it complains that the CORS header is missing, I have nginx setup to add the CORS header:

#
# Wide-open CORS config for nginx
#
location /upload {

      proxy_pass http://ejabberd-upload-handler;

      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      tcp_nodelay on;

     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
     }
     if ($request_method = 'PUT') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
     }

}

**Comment by sualko** [comment]
@PeterEdens please open a new issue for that and add your error message.

**Pull request merged**
