### PR TITLE
Last Message Correction (XEP-0308)

### LINKED ISSUE #746: XEP-0308: Last Message Correction
[XEP-0308](https://xmpp.org/extensions/xep-0308.html) defines a method for indicating that a message is a correction of the last sent message.

### PR DESCRIPTION
**Pull request by sualko**
Since MAM needs special treatment, this pr will focus only on normal chat messages.

- [x] process incoming message corrections
- [x] allow to fix the last outgoing message with `/fix` command
- [x] mark edited message with icon
- [x] add chat message menu
- [x] add chat message history

fix #746 and close #1008

Specification: https://xmpp.org/extensions/xep-0308.html

2021-12-31 14 49 08 localhost da7b6cae90d3
2021-12-31 14 49 33 localhost 58ee6a2d9e13

### CODE REVIEW

**Comment by sualko** [comment]
@mightymop this pr doesn't have all functions from your pr, but message correction works in a "live" chat. Hope that's ok for you.

**Comment by Neustradamus** [comment]
@sualko, @mightymop: Good job, nice! :)

@mightymop: What do you think?
Do you want other improvements based on your work?

**Comment by mightymop** [comment]
> @sualko, @mightymop: Good job, nice! :)
> 
> @mightymop: What do you think? Do you want other improvements based on your work?

I would like to see XEP-424 Message Retraction ;)

**Comment by mightymop** [comment]
> @mightymop this pr doesn't have all functions from your pr, but message correction works in a "live" chat. Hope that's ok for you.

i will have a look into your work in the next days... thx

**Pull request merged**
