### PR TITLE
Add an option to retrieve all the images from the avatar ? Even if users are offline

### PR DESCRIPTION
**Pull request by Ludovicis**
It's possible to add an option to retrieve all the images from the avatar, please ? (With a warning for the performance for example...)
Even if users are offline
This option will be in administration panel or in personnal panel

Thanks,

### CODE REVIEW

**Comment by sualko** [comment]
What's that?

**Comment by Ludovicis** [comment]
Hello Sualko,

Want more explanations?

**Comment by sualko** [comment]
Yes, that would be great, because you tried to merge the refactoring branch.

**Comment by Ludovicis** [comment]
sorry ;( I just wanted to add a pull. I am not very good with github...

**Comment by sualko** [comment]
You use a pull request if you like to contribute code, for everything else use issues, as you did.

**Comment by Ludovicis** [comment]
ok sorry again

**Pull request closed without merging**
