### PR TITLE
HTTP File Upload (XEP-0363)

### LINKED ISSUE #349: Support XEP-0363 HTTP_Upload
http_upload is supported by Conversations in Android, Monal in iOS and OSX as well as Gajim for Linux and is proposed standard xep-0363.

This is a very useful XEP for asynchronous picture sharing (Send picture while receiver is offline)

I would like to deploy a web chat for our users, but I have currently found no web client supporting this XEP.

Does Jsxc team plan to support http upload in the future?
##

### PR DESCRIPTION
**Pull request by sualko**
http://xmpp.org/extensions/xep-0363.html

fix #349
obsolete #352

### CODE REVIEW

**Comment by kamphaus** [comment]
In jsxc.lib.xmpp.httpUpload.js you call uploadFile with the data.put URL, but you never use the data.get URL.
According to XEP-0363 the get URL is where after a successful upload you can download the file.

**Comment by sualko** [comment]
WIP=work in progress

**Comment by sualko** [comment]
@kamphaus @sngyai @tristan-k @peterhoth @kitschkite @pmehul55 I think http upload is ready for testing.

I created a [wiki page](https://github.com/jsxc/jsxc/wiki/File-transfer) to collect important information around file transfer. Please feel free to add more helpful hints and tricks.

**Comment by tristan-k** [comment]
Great news! Is there a easy way to check out the current master branch with owncloud without compiling? There is no information about that at https://github.com/jsxc/jsxc/wiki/Install-ojsxc-%28owncloud%29.

**Comment by sualko** [comment]
@tristan-k  You can try to replace the jsxc (ojsxc/js/jsxc) folder with this [zip archive](https://github.com/jsxc/jsxc/files/684757/jsxc-3.1.0-httpUpload.zip).

**Comment by tristan-k** [comment]
Is the branch only compatible with owncloud 9 upwards? Because I'm on ownCloud 8.2.9 and unable to activate the app.

**Comment by sualko** [comment]
This is only an archive of the core and not an ready to go oc app. As I said you have to replace the folder in your ojsxc app folder.

**Pull request merged**
