### PR TITLE
fix vcard parsing into list

### PR DESCRIPTION
**Pull request by mightymop**
old implementation did not parse correctly all data into the list for template creation

### CODE REVIEW

**Comment by sualko** [comment]
Can you elaborate a bit more, which issue this pr is fixing?

**Comment by mightymop** [comment]
> 
> 
> Can you elaborate a bit more, which issue this pr is fixing?

with your old implementation the conversion xml > json does not take all fields of the vcard... dont know why but there were some fields missed. mostly in deeper xml tags like adr and tel ...

**Comment by mightymop** [comment]
i also added some css style to the vcard dialog now

**Comment by sualko** [comment]
> does not take all fields of the vcard

Can you provide a copy of such an vcard?

Btw you don't have to squash your commits, because I do it once when merging and having multiple commits also helps to track your changes.

**Comment by mightymop** [comment]
> 
> 
> > does not take all fields of the vcard
> 
> Can you provide a copy of such an vcard?
> 
> Btw you don't have to squash your commits, because I do it once when merging and having multiple commits also helps to track your changes.

ok.. on other repos they mostly want it squashed...

**Comment by mightymop** [comment]
closed for PR: https://github.com/jsxc/jsxc/pull/984

**Pull request closed without merging**
