### PR TITLE
[WIP] New design

### PR DESCRIPTION
**Pull request by sualko**
This pr is to inform you about the current state of our new design.

screenshot2

- [x] remove redundant elements
- [x] update unread
- [x] update last msg
- [x] roster bottom
- [x] window design

It is currently not ready to test it with owncloud. 

@LEDfan @jancborchardt

### CODE REVIEW

**Comment by sualko** [comment]
screenshot3

@Zauberstuhl How do you like the new design? Do you think this (in dark) will also fit in Diaspora?

**Comment by Zauberstuhl** [comment]
@sualko we moved to bootstrap3 so I am pretty sure that will fit. I like the new design :+1:

**Comment by sualko** [comment]
screen shot 2015-09-08 at 10 33 56
screen shot 2015-09-08 at 12 32 14

I am thinking about to make the roster wider on big screens. Any opinions?

The next big step is the window design. I am not sure, if light colours work here as well. I do not like the border, but otherwise it is hard to distinguish between window and background. A shadow would help, but in this case I think the roster needs one as well.

screen shot 2015-09-08 at 13 22 30
screen shot 2015-09-08 at 13 27 41

**Comment by jancborchardt** [comment]
@sualko the roster is wide enough it seems. :) I wouldn’t necessarily make it wider on big screens.

One thing: Can you always test with latest master? Then you get a better feeling of how it will look with the latest version. For example, the avatar placeholders should not use bold letters but light ones. Also, please submit a pull request to the avatar placeholder algorithm with your color fixes. :)

**Comment by jancborchardt** [comment]
Otherwise really nice, with the online dot, the color, spacing etc! :) 

The message box should not have a shadow as it looks strange and works just fine without.
* the individual messages don’t need a border
* the name in the header of the message box can be vertically centered with the avatar, as there is no second line with the latest message
* again – the message input field should be left-aligned instead of right. ;)

**Comment by sualko** [comment]
Designing stuff is really annoying... So many ways to do it....

screen shot 2015-09-17 at 16 25 49

screen shot 2015-09-17 at 16 26 11

**Comment by jancborchardt** [comment]
@sualko nice! The message window of the top one is better (with the light background) but combined with the message window header of the bottom one (also the lighter one).

**Comment by hwdfld** [comment]
Looks quite good :) I would suggest minimizing the header in the chat window by cutting of the user icon at the bottom (fading it out). And offline users should be hidden by default. Instead of showing "Online" at the bottom right for me as a user, maybe one should replace it with my name (no the best solution I know, because my name is already been shown at the top right, but more consistent with the buddy list layout). Btw showing "Ilias" ... does it mean there is some integration going on? That would be awesome :D

**Comment by sualko** [comment]
@hwdfl It is a little bit neglected and currently only for the 4.x branch, but here you go: https://github.com/jsxc/jsxc.ilias. Maybe you are also interested in our sogo version: https://github.com/jsxc/jsxc.sogo

**Comment by sualko** [comment]
Related #137, #133

**Comment by sualko** [comment]
@jancborchardt I knew that you would say that, but a little survey showed, that user do not like if everything is white without any contrast (true for jsxc and owncloud btw). I also think that the dark bar make sense, because we have to delimit to three directions. @LEDfan What do you think?

screen shot 2015-09-24 at 15 21 14

Of course the emoticons and presence menu are normally folded. 

@hwdfld I also tried to minimize the header, but it looks weird.

**Comment by sualko** [comment]
I think we getting closer to a merging state. The only thing missing is some clean up and testing. Of course there are other tasks, like reducing dialogs, login procedure, ... but the new design should be basically done.

Desktop:
screen shot 2015-10-07 at 14 16 11

Mobile:
tmp_14227-screenshot_2015-10-07-14-16-371424115086

**Comment by MarcelWaldvogel** [comment]
Looks great. The hangup overlay in the mobile environment would cover head or eyes of the peer. Can this be changed?

**Comment by sualko** [comment]
You can toggle the controls with a touch on the video. I think this is 
common and should be fine for most users.

**Comment by sualko** [comment]
This needs exhaustive testing, but I think it is good to merge.

**Comment by jancborchardt** [comment]
Great stuff! :)

Similar as @MarcelWaldvogel mentioned, I would say that the controls should be displayed on the bottom, centered. That would avoid any possible overlap as much as possible and also move the controls close to your own video feed.

**Comment by Zauberstuhl** [comment]
was pushed to latest diaspora dev-version. good job!

**Pull request merged**
